server:
  error:
    include-stacktrace: never

spring:
  application:
    name: springboot2-essentials
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl:auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app: Spring boot 2 essentials by DevDojo
  website: https://lucasvidoto.com
  github: https://github.com/lucasestanislau/springboot2-essentials

